/**
 * Demo seed data for presentation/demo mode.
 * Used as fallback when the API returns empty results (no Supabase connection or no real data).
 */

import type { SuggestionRow } from "@/lib/engine/suggestions";
import type { AuditLogRow } from "@/lib/engine/audit";

// Helper to create dates relative to "now" so demo data always looks fresh
function hoursAgo(h: number): string {
  return new Date(Date.now() - h * 60 * 60 * 1000).toISOString();
}
function hoursFromNow(h: number): string {
  return new Date(Date.now() + h * 60 * 60 * 1000).toISOString();
}

export const DEMO_SUGGESTIONS: SuggestionRow[] = [
  {
    id: "demo-sug-001",
    operator_id: "1",
    type: "waitlist",
    status: "pending",
    priority: 95,
    student_id: "stu-001",
    student_name: "Julian Sterling",
    instructor_id: "ins-001",
    instructor_name: "Sarah Jenkins",
    aircraft_id: "ac-001",
    aircraft_name: "Cessna 172S (N422PB)",
    location_id: "loc-1",
    activity_type_id: "at-1",
    proposed_start: hoursFromNow(18),
    proposed_end: hoursFromNow(20),
    alternatives: [],
    rationale:
      "Best match for availability — solo nav slot opened, Sterling is #1 on waitlist with 3 days since last flight.",
    context: { stage: "PPL Stage 2", lesson: "Solo Navigation" },
    trigger_event: { type: "slot_opened", source: "maintenance_delay" },
    reviewed_by: null,
    reviewed_at: null,
    executed_at: null,
    reservation_id: null,
    created_at: hoursAgo(1),
    updated_at: hoursAgo(1),
  },
  {
    id: "demo-sug-002",
    operator_id: "1",
    type: "reschedule",
    status: "pending",
    priority: 88,
    student_id: "stu-002",
    student_name: "Alicia Moreno",
    instructor_id: "ins-002",
    instructor_name: "Capt. Miller",
    aircraft_id: "ac-002",
    aircraft_name: "Piper Archer (N811TS)",
    location_id: "loc-1",
    activity_type_id: "at-2",
    proposed_start: hoursFromNow(4),
    proposed_end: hoursFromNow(5.5),
    alternatives: [],
    rationale:
      "Replaces cancelled slot for N811TS. Maintains 48-hour proficiency window for instrument approach practice.",
    context: { program: "Instrument Rating", cancellation_reason: "Instructor sick" },
    trigger_event: { type: "cancellation", original_time: hoursFromNow(2) },
    reviewed_by: null,
    reviewed_at: null,
    executed_at: null,
    reservation_id: null,
    created_at: hoursAgo(2),
    updated_at: hoursAgo(2),
  },
  {
    id: "demo-sug-003",
    operator_id: "1",
    type: "next_lesson",
    status: "pending",
    priority: 75,
    student_id: "stu-003",
    student_name: "David Kim",
    instructor_id: "ins-001",
    instructor_name: "Sarah Jenkins",
    aircraft_id: "ac-003",
    aircraft_name: "Cessna 172SP (N558PB)",
    location_id: "loc-1",
    activity_type_id: "at-3",
    proposed_start: hoursFromNow(26),
    proposed_end: hoursFromNow(29),
    alternatives: [],
    rationale:
      "Completes cross-country requirement while weather window is optimal. Kim finished solo patterns yesterday.",
    context: { program: "Commercial Pilot", next_event: "XC Dual" },
    trigger_event: { type: "lesson_completed", completed_lesson: "Solo Patterns" },
    reviewed_by: null,
    reviewed_at: null,
    executed_at: null,
    reservation_id: null,
    created_at: hoursAgo(3),
    updated_at: hoursAgo(3),
  },
  {
    id: "demo-sug-004",
    operator_id: "1",
    type: "discovery",
    status: "pending",
    priority: 60,
    student_id: null,
    student_name: "Sarah Chen",
    instructor_id: "ins-002",
    instructor_name: "Capt. Miller",
    aircraft_id: "ac-001",
    aircraft_name: "Cessna 172S (N422PB)",
    location_id: "loc-1",
    activity_type_id: "at-4",
    proposed_start: hoursFromNow(48),
    proposed_end: hoursFromNow(49),
    alternatives: [],
    rationale:
      "Daylight-constrained intro flight. Saturday morning slot has best weather forecast and aircraft availability.",
    context: { prospect_email: "sarah.chen@email.com", type: "Intro Session" },
    trigger_event: { type: "discovery_request" },
    reviewed_by: null,
    reviewed_at: null,
    executed_at: null,
    reservation_id: null,
    created_at: hoursAgo(5),
    updated_at: hoursAgo(5),
  },
  {
    id: "demo-sug-005",
    operator_id: "1",
    type: "waitlist",
    status: "approved",
    priority: 90,
    student_id: "stu-004",
    student_name: "Marcus Chen",
    instructor_id: "ins-001",
    instructor_name: "Sarah Jenkins",
    aircraft_id: "ac-001",
    aircraft_name: "Cessna 172S (N422PB)",
    location_id: "loc-1",
    activity_type_id: "at-1",
    proposed_start: hoursAgo(4),
    proposed_end: hoursAgo(2),
    alternatives: [],
    rationale: "Waitlist position #1, matched to open solo slot. Approved by Capt. Miller.",
    context: { stage: "PPL Stage 3", lesson: "Solo Practice" },
    trigger_event: { type: "slot_opened" },
    reviewed_by: "Capt. Miller",
    reviewed_at: hoursAgo(6),
    executed_at: hoursAgo(6),
    reservation_id: "res-001",
    created_at: hoursAgo(8),
    updated_at: hoursAgo(6),
  },
  {
    id: "demo-sug-006",
    operator_id: "1",
    type: "waitlist",
    status: "pending",
    priority: 82,
    student_id: "stu-005",
    student_name: "Priya Nair",
    instructor_id: "ins-001",
    instructor_name: "Sarah Jenkins",
    aircraft_id: "ac-003",
    aircraft_name: "Cessna 172SP (N558PB)",
    location_id: "loc-1",
    activity_type_id: "at-1",
    proposed_start: hoursFromNow(32),
    proposed_end: hoursFromNow(34),
    alternatives: [],
    rationale:
      "Nair is approaching the 5-day proficiency window boundary. N558PB opened after a maintenance release — aircraft is rated for her stage. Waitlist position #2.",
    context: { stage: "PPL Stage 1", lesson: "Dual Navigation" },
    trigger_event: { type: "slot_opened", source: "maintenance_release" },
    reviewed_by: null,
    reviewed_at: null,
    executed_at: null,
    reservation_id: null,
    created_at: hoursAgo(0.5),
    updated_at: hoursAgo(0.5),
  },
  {
    id: "demo-sug-007",
    operator_id: "1",
    type: "next_lesson",
    status: "pending",
    priority: 70,
    student_id: "stu-006",
    student_name: "Liam Okafor",
    instructor_id: "ins-003",
    instructor_name: "Lt. Torres",
    aircraft_id: "ac-002",
    aircraft_name: "Piper Archer (N811TS)",
    location_id: "loc-1",
    activity_type_id: "at-3",
    proposed_start: hoursFromNow(44),
    proposed_end: hoursFromNow(45.5),
    alternatives: [],
    rationale:
      "Okafor completed hood work last session — instrument scan lesson is next in syllabus. N811TS is IFR-equipped; slot falls within optimal 48-hour reinforcement window.",
    context: { program: "Instrument Rating", next_event: "Hood Work — Partial Panel" },
    trigger_event: { type: "lesson_completed", completed_lesson: "Basic Instrument Scan" },
    reviewed_by: null,
    reviewed_at: null,
    executed_at: null,
    reservation_id: null,
    created_at: hoursAgo(4),
    updated_at: hoursAgo(4),
  },
  {
    id: "demo-sug-008",
    operator_id: "1",
    type: "discovery",
    status: "pending",
    priority: 55,
    student_id: null,
    student_name: "Tom Bradley",
    instructor_id: "ins-002",
    instructor_name: "Capt. Miller",
    aircraft_id: "ac-001",
    aircraft_name: "Cessna 172S (N422PB)",
    location_id: "loc-1",
    activity_type_id: "at-4",
    proposed_start: hoursFromNow(72),
    proposed_end: hoursFromNow(73),
    alternatives: [],
    rationale:
      "Prospect inquiry received via website. Slot is within civil twilight, VFR forecast, and N422PB has no conflicts. Capt. Miller confirmed availability for intro flights this block.",
    context: { prospect_email: "tom.bradley@email.com", type: "Discovery Flight" },
    trigger_event: { type: "discovery_request" },
    reviewed_by: null,
    reviewed_at: null,
    executed_at: null,
    reservation_id: null,
    created_at: hoursAgo(6),
    updated_at: hoursAgo(6),
  },
  {
    id: "demo-sug-009",
    operator_id: "1",
    type: "reschedule",
    status: "approved",
    priority: 91,
    student_id: "stu-007",
    student_name: "Elena Rodriguez",
    instructor_id: "ins-002",
    instructor_name: "Capt. Miller",
    aircraft_id: "ac-002",
    aircraft_name: "Piper Archer (N811TS)",
    location_id: "loc-1",
    activity_type_id: "at-2",
    proposed_start: hoursAgo(2),
    proposed_end: hoursAgo(0.5),
    alternatives: [],
    rationale:
      "Rodriguez had a morning slot cancelled due to ATC ground stop. Rescheduled into afternoon opening — same aircraft, same instructor, preserving her instrument approach currency.",
    context: { program: "Instrument Rating", cancellation_reason: "ATC ground stop" },
    trigger_event: { type: "cancellation", original_time: hoursAgo(5) },
    reviewed_by: "Lt. Torres",
    reviewed_at: hoursAgo(3),
    executed_at: hoursAgo(3),
    reservation_id: "res-009",
    created_at: hoursAgo(4),
    updated_at: hoursAgo(3),
  },
  {
    id: "demo-sug-010",
    operator_id: "1",
    type: "waitlist",
    status: "executed",
    priority: 88,
    student_id: "stu-003",
    student_name: "David Kim",
    instructor_id: "ins-003",
    instructor_name: "Lt. Torres",
    aircraft_id: "ac-004",
    aircraft_name: "Diamond DA40 (N204TF)",
    location_id: "loc-1",
    activity_type_id: "at-1",
    proposed_start: hoursAgo(6),
    proposed_end: hoursAgo(4),
    alternatives: [],
    rationale:
      "Kim moved to #1 on waitlist after two ahead withdrew. N204TF match for Commercial stage dual XC — approved and reservation confirmed in FSP.",
    context: { stage: "Commercial Stage 1", lesson: "Dual XC" },
    trigger_event: { type: "slot_opened" },
    reviewed_by: "Sarah Jenkins",
    reviewed_at: hoursAgo(8),
    executed_at: hoursAgo(8),
    reservation_id: "res-010",
    created_at: hoursAgo(10),
    updated_at: hoursAgo(8),
  },
  {
    id: "demo-sug-011",
    operator_id: "1",
    type: "next_lesson",
    status: "declined",
    priority: 65,
    student_id: "stu-008",
    student_name: "Jamie Torres",
    instructor_id: "ins-001",
    instructor_name: "Sarah Jenkins",
    aircraft_id: "ac-001",
    aircraft_name: "Cessna 172S (N422PB)",
    location_id: "loc-1",
    activity_type_id: "at-3",
    proposed_start: hoursFromNow(36),
    proposed_end: hoursFromNow(37.5),
    alternatives: [],
    rationale:
      "Torres is next in syllabus for night currency — however, student requested to defer until next week. Declined by scheduler per student preference.",
    context: { program: "PPL", next_event: "Night Dual" },
    trigger_event: { type: "lesson_completed", completed_lesson: "Dual Simulated Instrument" },
    reviewed_by: "Capt. Miller",
    reviewed_at: hoursAgo(1),
    executed_at: null,
    reservation_id: null,
    created_at: hoursAgo(12),
    updated_at: hoursAgo(1),
  },
  {
    id: "demo-sug-012",
    operator_id: "1",
    type: "waitlist",
    status: "expired",
    priority: 40,
    student_id: "stu-009",
    student_name: "Noah Patel",
    instructor_id: "ins-002",
    instructor_name: "Capt. Miller",
    aircraft_id: "ac-003",
    aircraft_name: "Cessna 172SP (N558PB)",
    location_id: "loc-1",
    activity_type_id: "at-1",
    proposed_start: hoursAgo(46),
    proposed_end: hoursAgo(44),
    alternatives: [],
    rationale:
      "Patel was #3 on waitlist; slot was offered but no response within the 4-hour acceptance window. Suggestion expired automatically.",
    context: { stage: "PPL Stage 2", lesson: "Maneuvers" },
    trigger_event: { type: "slot_opened" },
    reviewed_by: null,
    reviewed_at: null,
    executed_at: null,
    reservation_id: null,
    created_at: hoursAgo(48),
    updated_at: hoursAgo(44),
  },
  {
    id: "demo-sug-013",
    operator_id: "1",
    type: "reschedule",
    status: "pending",
    priority: 78,
    student_id: "stu-010",
    student_name: "Sofia Reyes",
    instructor_id: "ins-001",
    instructor_name: "Sarah Jenkins",
    aircraft_id: "ac-001",
    aircraft_name: "Cessna 172S (N422PB)",
    location_id: "loc-1",
    activity_type_id: "at-2",
    proposed_start: hoursFromNow(8),
    proposed_end: hoursFromNow(9.5),
    alternatives: [],
    rationale:
      "Reyes had her solo flight scrubbed due to crosswind exceedance. Next suitable window opens in 8 hours with forecast winds 5kt — well within solo limits.",
    context: { stage: "PPL Stage 2", cancellation_reason: "Weather — crosswind limit exceeded" },
    trigger_event: { type: "cancellation", original_time: hoursAgo(1) },
    reviewed_by: null,
    reviewed_at: null,
    executed_at: null,
    reservation_id: null,
    created_at: hoursAgo(1),
    updated_at: hoursAgo(1),
  },
];

// Helper: days ago from midnight of "today"
function daysAgo(d: number, offsetHours = 0): string {
  const t = new Date();
  t.setHours(0, 0, 0, 0);
  t.setDate(t.getDate() - d);
  return new Date(t.getTime() + offsetHours * 60 * 60 * 1000).toISOString();
}

export const DEMO_ACTIVITY: AuditLogRow[] = [
  // ── TODAY ──────────────────────────────────────────────────────────────────
  {
    id: "demo-aud-001",
    operator_id: "1",
    event_type: "suggestion_created",
    entity_type: "suggestion",
    entity_id: "demo-sug-001",
    actor_id: "system",
    actor_type: "system",
    payload: { type: "waitlist", student: "Julian Sterling" },
    created_at: hoursAgo(1),
  },
  {
    id: "demo-aud-002",
    operator_id: "1",
    event_type: "suggestion_approved",
    entity_type: "suggestion",
    entity_id: "demo-sug-005",
    actor_id: "capt-miller",
    actor_type: "scheduler",
    payload: { type: "waitlist", student: "Marcus Chen" },
    created_at: hoursAgo(2),
  },
  {
    id: "demo-aud-003",
    operator_id: "1",
    event_type: "reservation_created",
    entity_type: "reservation",
    entity_id: "res-001",
    actor_id: "system",
    actor_type: "system",
    payload: { student: "Marcus Chen", aircraft: "N422PB" },
    created_at: hoursAgo(2),
  },
  {
    id: "demo-aud-004",
    operator_id: "1",
    event_type: "suggestion_created",
    entity_type: "suggestion",
    entity_id: "demo-sug-006",
    actor_id: "system",
    actor_type: "system",
    payload: { type: "waitlist", student: "Priya Nair" },
    created_at: hoursAgo(3),
  },
  {
    id: "demo-aud-005",
    operator_id: "1",
    event_type: "suggestion_approved",
    entity_type: "suggestion",
    entity_id: "demo-sug-009",
    actor_id: "lt-torres",
    actor_type: "scheduler",
    payload: { type: "reschedule", student: "Elena Rodriguez" },
    created_at: hoursAgo(3),
  },
  {
    id: "demo-aud-006",
    operator_id: "1",
    event_type: "reservation_created",
    entity_type: "reservation",
    entity_id: "res-009",
    actor_id: "system",
    actor_type: "system",
    payload: { student: "Elena Rodriguez", aircraft: "N811TS" },
    created_at: hoursAgo(3),
  },
  {
    id: "demo-aud-007",
    operator_id: "1",
    event_type: "suggestion_created",
    entity_type: "suggestion",
    entity_id: "demo-sug-013",
    actor_id: "system",
    actor_type: "system",
    payload: { type: "reschedule", student: "Sofia Reyes" },
    created_at: hoursAgo(4),
  },
  {
    id: "demo-aud-008",
    operator_id: "1",
    event_type: "notification_sent",
    entity_type: "notification",
    entity_id: "notif-001",
    actor_id: "system",
    actor_type: "system",
    payload: { recipient: "Marcus Chen", channel: "email" },
    created_at: hoursAgo(2),
  },

  // ── YESTERDAY ──────────────────────────────────────────────────────────────
  {
    id: "demo-aud-009",
    operator_id: "1",
    event_type: "suggestion_created",
    entity_type: "suggestion",
    entity_id: "demo-sug-010",
    actor_id: "system",
    actor_type: "system",
    payload: { type: "waitlist", student: "David Kim" },
    created_at: daysAgo(1, 9),
  },
  {
    id: "demo-aud-010",
    operator_id: "1",
    event_type: "suggestion_created",
    entity_type: "suggestion",
    entity_id: "demo-sug-011",
    actor_id: "system",
    actor_type: "system",
    payload: { type: "next_lesson", student: "Jamie Torres" },
    created_at: daysAgo(1, 10),
  },
  {
    id: "demo-aud-011",
    operator_id: "1",
    event_type: "suggestion_approved",
    entity_type: "suggestion",
    entity_id: "demo-sug-010",
    actor_id: "sarah-jenkins",
    actor_type: "scheduler",
    payload: { type: "waitlist", student: "David Kim" },
    created_at: daysAgo(1, 11),
  },
  {
    id: "demo-aud-012",
    operator_id: "1",
    event_type: "suggestion_declined",
    entity_type: "suggestion",
    entity_id: "demo-sug-011",
    actor_id: "capt-miller",
    actor_type: "scheduler",
    payload: { type: "next_lesson", reason: "Student requested deferral to next week" },
    created_at: daysAgo(1, 12),
  },
  {
    id: "demo-aud-013",
    operator_id: "1",
    event_type: "reservation_created",
    entity_type: "reservation",
    entity_id: "res-010",
    actor_id: "system",
    actor_type: "system",
    payload: { student: "David Kim", aircraft: "N204TF" },
    created_at: daysAgo(1, 11),
  },
  {
    id: "demo-aud-014",
    operator_id: "1",
    event_type: "reservation_created",
    entity_type: "reservation",
    entity_id: "res-011",
    actor_id: "system",
    actor_type: "system",
    payload: { student: "Alicia Moreno", aircraft: "N811TS" },
    created_at: daysAgo(1, 14),
  },
  {
    id: "demo-aud-015",
    operator_id: "1",
    event_type: "notification_sent",
    entity_type: "notification",
    entity_id: "notif-002",
    actor_id: "system",
    actor_type: "system",
    payload: { recipient: "David Kim", channel: "sms" },
    created_at: daysAgo(1, 11),
  },

  // ── 2 DAYS AGO ─────────────────────────────────────────────────────────────
  {
    id: "demo-aud-016",
    operator_id: "1",
    event_type: "suggestion_created",
    entity_type: "suggestion",
    entity_id: "demo-sug-012",
    actor_id: "system",
    actor_type: "system",
    payload: { type: "waitlist", student: "Noah Patel" },
    created_at: daysAgo(2, 8),
  },
  {
    id: "demo-aud-017",
    operator_id: "1",
    event_type: "suggestion_created",
    entity_type: "suggestion",
    entity_id: "demo-sug-007",
    actor_id: "system",
    actor_type: "system",
    payload: { type: "next_lesson", student: "Liam Okafor" },
    created_at: daysAgo(2, 9),
  },
  {
    id: "demo-aud-018",
    operator_id: "1",
    event_type: "suggestion_approved",
    entity_type: "suggestion",
    entity_id: "demo-sug-old-2",
    actor_id: "capt-miller",
    actor_type: "scheduler",
    payload: { type: "discovery", student: "Marcus Chen" },
    created_at: daysAgo(2, 13),
  },
  {
    id: "demo-aud-019",
    operator_id: "1",
    event_type: "reservation_created",
    entity_type: "reservation",
    entity_id: "res-old-3",
    actor_id: "system",
    actor_type: "system",
    payload: { student: "Marcus Chen", aircraft: "N422PB", type: "Discovery Flight" },
    created_at: daysAgo(2, 13),
  },
  {
    id: "demo-aud-020",
    operator_id: "1",
    event_type: "notification_sent",
    entity_type: "notification",
    entity_id: "notif-003",
    actor_id: "system",
    actor_type: "system",
    payload: { recipient: "Noah Patel", channel: "email", note: "Waitlist slot offer — 4hr window" },
    created_at: daysAgo(2, 8),
  },
];
