/**
 * Demo seed data for presentation/demo mode.
 * Used as fallback when the API returns empty results (no Supabase connection or no real data).
 */

import type { SuggestionRow } from "@/lib/engine/suggestions";
import type { AuditLogRow } from "@/lib/engine/audit";

// Helper to create dates relative to "now" so demo data always looks fresh
function hoursAgo(h: number): string {
  return new Date(Date.now() - h * 60 * 60 * 1000).toISOString();
}
function hoursFromNow(h: number): string {
  return new Date(Date.now() + h * 60 * 60 * 1000).toISOString();
}

export const DEMO_SUGGESTIONS: SuggestionRow[] = [
  {
    id: "demo-sug-001",
    operator_id: "1",
    type: "waitlist",
    status: "pending",
    priority: 95,
    student_id: "stu-001",
    student_name: "Julian Sterling",
    instructor_id: "ins-001",
    instructor_name: "Sarah Jenkins",
    aircraft_id: "ac-001",
    aircraft_name: "Cessna 172S (N422PB)",
    location_id: "loc-1",
    activity_type_id: "at-1",
    proposed_start: hoursFromNow(18),
    proposed_end: hoursFromNow(20),
    alternatives: [],
    rationale:
      "Best match for availability — solo nav slot opened, Sterling is #1 on waitlist with 3 days since last flight.",
    context: { stage: "PPL Stage 2", lesson: "Solo Navigation" },
    trigger_event: { type: "slot_opened", source: "maintenance_delay" },
    reviewed_by: null,
    reviewed_at: null,
    executed_at: null,
    reservation_id: null,
    created_at: hoursAgo(1),
    updated_at: hoursAgo(1),
  },
  {
    id: "demo-sug-002",
    operator_id: "1",
    type: "reschedule",
    status: "pending",
    priority: 88,
    student_id: "stu-002",
    student_name: "Alicia Moreno",
    instructor_id: "ins-002",
    instructor_name: "Capt. Miller",
    aircraft_id: "ac-002",
    aircraft_name: "Piper Archer (N811TS)",
    location_id: "loc-1",
    activity_type_id: "at-2",
    proposed_start: hoursFromNow(4),
    proposed_end: hoursFromNow(5.5),
    alternatives: [],
    rationale:
      "Replaces cancelled slot for N811TS. Maintains 48-hour proficiency window for instrument approach practice.",
    context: { program: "Instrument Rating", cancellation_reason: "Instructor sick" },
    trigger_event: { type: "cancellation", original_time: hoursFromNow(2) },
    reviewed_by: null,
    reviewed_at: null,
    executed_at: null,
    reservation_id: null,
    created_at: hoursAgo(2),
    updated_at: hoursAgo(2),
  },
  {
    id: "demo-sug-003",
    operator_id: "1",
    type: "next_lesson",
    status: "pending",
    priority: 75,
    student_id: "stu-003",
    student_name: "David Kim",
    instructor_id: "ins-001",
    instructor_name: "Sarah Jenkins",
    aircraft_id: "ac-003",
    aircraft_name: "Cessna 172SP (N558PB)",
    location_id: "loc-1",
    activity_type_id: "at-3",
    proposed_start: hoursFromNow(26),
    proposed_end: hoursFromNow(29),
    alternatives: [],
    rationale:
      "Completes cross-country requirement while weather window is optimal. Kim finished solo patterns yesterday.",
    context: { program: "Commercial Pilot", next_event: "XC Dual" },
    trigger_event: { type: "lesson_completed", completed_lesson: "Solo Patterns" },
    reviewed_by: null,
    reviewed_at: null,
    executed_at: null,
    reservation_id: null,
    created_at: hoursAgo(3),
    updated_at: hoursAgo(3),
  },
  {
    id: "demo-sug-004",
    operator_id: "1",
    type: "discovery",
    status: "pending",
    priority: 60,
    student_id: null,
    student_name: "Sarah Chen",
    instructor_id: "ins-002",
    instructor_name: "Capt. Miller",
    aircraft_id: "ac-001",
    aircraft_name: "Cessna 172S (N422PB)",
    location_id: "loc-1",
    activity_type_id: "at-4",
    proposed_start: hoursFromNow(48),
    proposed_end: hoursFromNow(49),
    alternatives: [],
    rationale:
      "Daylight-constrained intro flight. Saturday morning slot has best weather forecast and aircraft availability.",
    context: { prospect_email: "sarah.chen@email.com", type: "Intro Session" },
    trigger_event: { type: "discovery_request" },
    reviewed_by: null,
    reviewed_at: null,
    executed_at: null,
    reservation_id: null,
    created_at: hoursAgo(5),
    updated_at: hoursAgo(5),
  },
  {
    id: "demo-sug-005",
    operator_id: "1",
    type: "waitlist",
    status: "approved",
    priority: 90,
    student_id: "stu-004",
    student_name: "Marcus Chen",
    instructor_id: "ins-001",
    instructor_name: "Sarah Jenkins",
    aircraft_id: "ac-001",
    aircraft_name: "Cessna 172S (N422PB)",
    location_id: "loc-1",
    activity_type_id: "at-1",
    proposed_start: hoursAgo(4),
    proposed_end: hoursAgo(2),
    alternatives: [],
    rationale: "Waitlist position #1, matched to open solo slot. Approved by Capt. Miller.",
    context: { stage: "PPL Stage 3", lesson: "Solo Practice" },
    trigger_event: { type: "slot_opened" },
    reviewed_by: "Capt. Miller",
    reviewed_at: hoursAgo(6),
    executed_at: hoursAgo(6),
    reservation_id: "res-001",
    created_at: hoursAgo(8),
    updated_at: hoursAgo(6),
  },
];

export const DEMO_ACTIVITY: AuditLogRow[] = [
  {
    id: "demo-aud-001",
    operator_id: "1",
    event_type: "suggestion_created",
    entity_type: "suggestion",
    entity_id: "demo-sug-001",
    actor_id: "system",
    actor_type: "system",
    payload: { type: "waitlist", student: "Julian Sterling" },
    created_at: hoursAgo(1),
  },
  {
    id: "demo-aud-002",
    operator_id: "1",
    event_type: "suggestion_approved",
    entity_type: "suggestion",
    entity_id: "demo-sug-005",
    actor_id: "capt-miller",
    actor_type: "scheduler",
    payload: { type: "waitlist", student: "Marcus Chen" },
    created_at: hoursAgo(2),
  },
  {
    id: "demo-aud-003",
    operator_id: "1",
    event_type: "reservation_created",
    entity_type: "reservation",
    entity_id: "res-001",
    actor_id: "system",
    actor_type: "system",
    payload: { student: "Marcus Chen", aircraft: "N422PB" },
    created_at: hoursAgo(2),
  },
  {
    id: "demo-aud-004",
    operator_id: "1",
    event_type: "notification_sent",
    entity_type: "notification",
    entity_id: "notif-001",
    actor_id: "system",
    actor_type: "system",
    payload: { recipient: "Marcus Chen", channel: "email" },
    created_at: hoursAgo(2),
  },
  {
    id: "demo-aud-005",
    operator_id: "1",
    event_type: "suggestion_created",
    entity_type: "suggestion",
    entity_id: "demo-sug-002",
    actor_id: "system",
    actor_type: "system",
    payload: { type: "reschedule", student: "Alicia Moreno" },
    created_at: hoursAgo(3),
  },
  {
    id: "demo-aud-006",
    operator_id: "1",
    event_type: "suggestion_declined",
    entity_type: "suggestion",
    entity_id: "demo-sug-old",
    actor_id: "capt-miller",
    actor_type: "scheduler",
    payload: { type: "next_lesson", reason: "Student requested different time" },
    created_at: hoursAgo(26),
  },
  {
    id: "demo-aud-007",
    operator_id: "1",
    event_type: "suggestion_approved",
    entity_type: "suggestion",
    entity_id: "demo-sug-old-2",
    actor_id: "capt-miller",
    actor_type: "scheduler",
    payload: { type: "discovery", student: "Jamie Torres" },
    created_at: hoursAgo(27),
  },
  {
    id: "demo-aud-008",
    operator_id: "1",
    event_type: "reservation_created",
    entity_type: "reservation",
    entity_id: "res-old-2",
    actor_id: "system",
    actor_type: "system",
    payload: { student: "Jamie Torres", aircraft: "N558PB", type: "Discovery Flight" },
    created_at: hoursAgo(27),
  },
];
